### [회원 - 회원 가입] 고객 회원 가입 API
POST http://localhost:8080/api/members/signup
Content-Type: application/json

{
  "nickname": "iAmCustomer",
  "name": "나고객",
  "phone": "01012345678",
  "password": "password123!",
  "memberType": "CUSTOMER"
}


### [회원 - 회원 가입] 점주 회원 가입 API
POST http://localhost:8080/api/members/signup
Content-Type: application/json

{
  "nickname": "iAmOwner",
  "name": "나점주",
  "phone": "01012345678",
  "password": "password123!",
  "memberType": "OWNER"
}


### [고객 - 예약] 예약을 요청하는 API
POST http://localhost:8080/customer/api/reservations?customerId=1
Content-Type: application/json

{
  "restaurantId": 3,
  "reservationCustomerInput": {
    "visitDateTime": "2023-01-26T22:00:00",
    "visitorCount": 2,
    "memo": "단무지는 빼주세요~"
  }
}


### [점주 - 식당] 식당 등록 API
POST http://localhost:8080/owner/api/restaurants?ownerId=2
Content-Type: application/json

{
  "foodType": "KOREAN",
  "name": "유명 레스토랑",
  "capacity": 6,
  "openTime": "11:00",
  "lastOrderTime": "21:00",
  "location": "서울특별시 강남구 어딘가로 123 무슨빌딩 1층",
  "description": "우리는 유명한 한식당입니다.",
  "phone": "0211112222",
  "menuList": [
    {
      "name": "맛있는 밥",
      "price": 10000,
      "description": "맛있어용"
    },
    {
      "name": "맛있는 국",
      "price": 20000,
      "description": "맛있어용"
    }
  ],
  "closingDays": [
    {
      "dayOfWeek": "MONDAY"
    }
  ]
}


### [예약] 날짜와 인원수를 통해 식당의 예약가능 시간들을 조회하는 API
GET http://localhost:8080/customer/api/reservations/available-times?restaurantId=3&date=2023-01-29&visitorCount=2


### [고객 - 예약] 예약을 요청하는 API
POST http://localhost:8080/customer/api/reservations?customerId=1
Content-Type: application/json

{
  "restaurantId": 3,
  "reservationCustomerInput": {
    "visitDateTime": "2023-01-20T16:00:00",
    "visitorCount": 4,
    "memo": "단무지는 빼주세요~"
  }
}


### [점주 - 예약] 예약을 확정하는 API
PATCH http://localhost:8080/owner/api/reservations/5?ownerId=2
Content-Type: application/json

{
  "status": "confirm"
}


### [점주 - 예약] 예약을 취소하는 API
PATCH http://localhost:8080/owner/api/reservations/4?ownerId=2
Content-Type: application/json

{
  "status": "cancel"
}


### [점주 - 예약] 예약을 방문완료로 변경하는 API
PATCH http://localhost:8080/owner/api/reservations/5?ownerId=2
Content-Type: application/json

{
  "status": "visit"
}

### 레스토랑 목록 paging조회
GET http://localhost:8080/customer/api/restaurants?page=0&size=3


### [점주 - 예약] 예약을 노쇼로 변경하는 API
PATCH http://localhost:8080/owner/api/reservations/5?ownerId=2
Content-Type: application/json

{
  "status": "no-show"
}

